### PR TITLE
Plugin names dosen't contain '/'

### PR DESCRIPTION
**Pull request by pedroluislopez**

### CODE REVIEW

**Comment by ganto** [comment]
@drybjed Thanks for the notification

@pedroluislopez Not sure what the reason for this is. However, I never had any issues being it there. The last commit cf18bb1517884a6b04ec6dcf6a2a0aa007a7cf08 changing this line is from you

**Comment by ganto** [comment]
Ok, I looked into the code again. [elasticsearch-plugins](https://docs.debops.org/en/latest/ansible/roles/ansible-elasticsearch/docs/defaults-detailed.html#elasticsearch-plugins) lists `com.sksamuel.elasticsearch/elasticsearch-river-redis/1.1.0` as an example plugin name. The `split("/")` may cut the first part. 

Although I wrote the documentation in the new format, I mostly copied the content from the previous docs (see [debops.elasticsearch.rst](https://github.com/debops/docs/blame/968100d21025d7d7e95eb0b951200dc9dd246350/docs/ansible/roles/debops.elasticsearch.rst#L109)). Maybe the naming scheme changed in the meantime or this is only valid for ES 1.x?

@pedroluislopez Can you please specify what problem this PR solves? Which ES version are you using?

**Comment by pedroluislopez** [comment]
@ganto The output for `bin/plugin list` in elasticsearch 2.4 is:

```
/usr/share/elasticsearch# bin/plugin list
Installed plugins in /usr/share/elasticsearch/plugins:
    - discovery-multicast
```

However, this code fails with elasticsearch 2.4 when you run the role for the second time:

```
- name: Install plugins by name
  shell: 'bin/plugin {{ "-i" if (elasticsearch__version_major | int == 1) else "install" }} {{ item.name }}'
  args:
    chdir: '{{ elasticsearch_path_home }}'
  when: (item.url is undefined or not item.url) and
        (item.delete is undefined or not item.delete) and
        not item.name.split('/')[1] in elasticsearch_register_installed_plugins.stdout
  with_flattened:
    - '{{ elasticsearch_plugins }}'
    - '{{ [ { "name": "discovery-multicast" } ]
          if ((elasticsearch__version_major | int == 2) and elasticsearch_discovery_multicast_enabled|d(False))
          else [] }}'
notify: [ 'Restart Elasticsearch' ]
```

Because `item.name.split('/')[1]` of `discovery-multicast` is a empty string, and it try install a plugin again.

**Comment by pedroluislopez** [comment]
@ganto @drybjed  I have done a fix in ordet to support plugin names with or without slash char.

**Comment by ganto** [comment]
Looks fine to me :+1:

**Pull request merged**
